### ISSUE TITLE
Breaks built-in storybook addons

### ISSUE THREAD

**Issue by yogaraptor** [kadirahq/storybook-addon-options#12]
Installing this addon somehow disables the linkTo and actions addons which come with storybook.

Steps to reproduce:
1. `create-react-app my-app && cd my-app && getstorybook && yarn add @kadira/storybook-addon-options && yarn storybook`
2. The action logger should be visible in the bottom panel and be showing logs for clicks on the button.
3. `yarn add @kadira/storybook-addon-options`
4. Add the `.storybook/addons.js` file and content to `.storybook/config.js` as listed in this addon's README, tweaking the config to show at least the bottom panel.
4. The bottom panel now just shows a message "No panels available". The link from the Welcome story to the Button story now no longer works either.

**Comment by arunoda** [comment]
@mnmtanish could you have a look at this?

**Comment by dptoot** [comment]
Without delving too much into the source code, it looks as though the addition of the addons.js file to the config directory may wipe the default registered addons.

@itsravenous 
I was able to resolve this by adding the default addons, from the pre-installed modules, in the addons.js file.

addons.js
```
import '@kadira/storybook-addon-options/register';
import '@kadira/storybook-addon-links/register';
import '@kadira/storybook-addon-actions/register';
```

**Comment by yogaraptor** [comment]
Confirmed, thanks! See also [react-storybook#192](https://github.com/storybooks/react-storybook/issues/192)
