### ISSUE TITLE
Options not always working

### ISSUE THREAD

**Issue by jamesstar89** [kadirahq/storybook-addon-options#16]
Hello,

I'm using Storybook with add-ons from home and work, and my home version isn't working.

I have set up addons.js file with the following...

```js
import '@kadira/storybook/addons';
import '@kadira/storybook-addon-options/register';
import '@kadira/storybook-addon-knobs/register';
import '@kadira/storybook-addon-actions/register';
```
Also set up my config.js with following...

```js
import * as storybook from '@kadira/storybook';
import { setOptions } from '@kadira/storybook-addon-options';

setOptions({
  name: 'Project name',
  url: '',
  goFullScreen: false,
  showLeftPanel: true,
  showDownPanel: false,
  showSearchBox: false,
  downPanelInRight: false,
  sortStoriesByKind: false
});

function loadStories() {
  requires ...
}

storybook.configure(loadStories, module);
```
Any ideas? All I get is the same "React Storybook" button above and the below panel says - "No Panels Available" Tried various combinations to get this to work, just feel I'm missing some detail? Thanks.

**Comment by ndelangen** [comment]
Any messages in the browser console or terminal you can see?

**Comment by jamesstar89** [comment]
Just the usual start up messages, both in browser console and terminal, was thinking whether it was a caching issue, or node version or something?

**Comment by ndelangen** [comment]
What's your node, npm, storybook, react version, system info etc?

Are the other addons working as expected?

**Comment by jamesstar89** [comment]
Installed same version as at work, and working now.

Node 6.9.4
npm 3.10.10

Thanks

**Comment by ndelangen** [comment]
So the problem went away with updating to node 6.9.4 and npm 3.10.10 ?
Would like to know the version you had before.

**Comment by jamesstar89** [comment]
Okay, will find out and reply here.

**Comment by jamesstar89** [comment]
Node 6.1.0
