### ISSUE TITLE
Need to press keyboard shortcuts twice with empty query string

### ISSUE THREAD

**Issue by usulpro** [kadirahq/storybook-addon-options#9]
_steps to reproduce:_

1 set any option e.g. `goFullScreen: true,`
2 open storybook by url like http://localhost:9001/
3 press `Ctrl-Shift-F`
4 press `Ctrl-Shift-F` again

_expected behavior:_

after [3] storybook should exit from `fullscreen mode`

_real behavior:_

after [3] it flashes 'non fullscreen mode' and then it goes back to `fullscreen`
next pressing  `Ctrl-Shift-F` works properly

_example:_

https://sm-react.github.io/react-theming/

(it starts in `fullscreen mode`)

**Comment by usulpro** [comment]
Now it works properly, thank you!

**Comment by arunoda** [comment]
BTW: How does it suppose get fixed?
Did I miss some discussion related to this?

**Comment by usulpro** [comment]
@arunoda 
after the last release it starts to work properly
I just noticed it and wrote :)

**Comment by arunoda** [comment]
Awesome. I think we can close this now.
